# 配置文件

[download]
## 下载位置，相对和绝对路径：
##  - Windows: D:\test 或 D:/test
##  - macOS, Linux: /home/user/test
path = 'C:\Users\yui\Desktop\Wallpaper'

[proxy]
## proxy [socks5://][127.0.0.1:]<1-65535>; 代理
## 协议：socks4, socks5, http, https
socket = "socks5://127.0.0.1:7891"
## 设置是否启用代理
enable = true
